site_name: Obsidian mkdocs

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - django

# Extensions
markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs
  - mkdocs-click

plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-]'
  - roamlinks
  - mermaid2
  - jieba

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
